import { describe, it, expect, afterEach } from "vitest";
import * as http from "node:http";
import * as net from "node:net";
import { randomBytes } from "node:crypto";
import { connectUpstreamWebSocket } from "../ws-upstream.js";
import { connectWebSocket } from "./ws-test-client.js";
import { computeAcceptKey, upgradeToWebSocket, WebSocketConnection } from "../ws-framing.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function createMaskedFrame(opcode: number, payload: Buffer): Buffer {
  const maskKey = randomBytes(4);
  const masked = Buffer.from(payload);
  for (let i = 0; i < masked.length; i++) {
    masked[i] ^= maskKey[i % 4];
  }

  let header: Buffer;
  if (payload.length < 126) {
    header = Buffer.alloc(2);
    header[0] = 0x80 | opcode;
    header[1] = 0x80 | payload.length;
  } else {
    header = Buffer.alloc(4);
    header[0] = 0x80 | opcode;
    header[1] = 0x80 | 126;
    header.writeUInt16BE(payload.length, 2);
  }

  return Buffer.concat([header, maskKey, masked]);
}

const OP_TEXT = 0x1;
const OP_CLOSE = 0x8;
const OP_PING = 0x9;
const OP_PONG = 0xa;

const WS_KEY = "dGhlIHNhbXBsZSBub25jZQ==";
// Independent RFC 6455 section 1.3 handshake example (not generated by our helper).
const EXPECTED_ACCEPT = "s3pPLMBiTxaQ9kYGzzhZRbK+xOo=";

/**
 * Spin up an HTTP server that upgrades to WebSocket via upgradeToWebSocket().
 * Returns the server, its port, and a promise that resolves to the
 * server-side WebSocketConnection once a client connects.
 */
function createTestServer(limits?: {
  maxMessageBytes?: number;
  maxBufferedBytes?: number;
  maxWriteBytes?: number;
  maskOutgoing?: boolean;
}): {
  server: http.Server;
  port: () => number;
  wsPromise: Promise<WebSocketConnection>;
} {
  let resolveWs: (ws: WebSocketConnection) => void;
  const wsPromise = new Promise<WebSocketConnection>((resolve) => {
    resolveWs = resolve;
  });

  const server = http.createServer();
  // Suppress ECONNRESET on any server connection during teardown
  server.on("connection", (socket) => {
    socket.on("error", () => {});
  });
  server.on("upgrade", (req, socket) => {
    socket.on("error", () => {});
    const ws = upgradeToWebSocket(req, socket as net.Socket, limits);
    resolveWs(ws);
  });

  server.listen(0); // random available port

  return {
    server,
    port: () => (server.address() as net.AddressInfo).port,
    wsPromise,
  };
}

/**
 * Open a raw TCP connection to the test server and send an HTTP upgrade
 * request.  Returns the socket and a promise that resolves with the full
 * HTTP 101 response line + headers once the blank line is received.
 */
function rawConnect(
  port: number,
  headers?: Record<string, string>,
): { socket: net.Socket; response: Promise<string> } {
  const socket = net.connect({ port, host: "127.0.0.1" });
  // Suppress ECONNRESET during teardown — the server may destroy the socket
  socket.on("error", () => {});

  const mergedHeaders: Record<string, string> = {
    Host: "localhost",
    Upgrade: "websocket",
    Connection: "Upgrade",
    "Sec-WebSocket-Version": "13",
    "Sec-WebSocket-Key": WS_KEY,
    ...headers,
  };

  const lines = [`GET / HTTP/1.1`];
  for (const [k, v] of Object.entries(mergedHeaders)) {
    lines.push(`${k}: ${v}`);
  }
  lines.push("", ""); // blank line terminates request

  socket.write(lines.join("\r\n"));

  const response = new Promise<string>((resolve) => {
    let buf = "";
    const onData = (chunk: Buffer) => {
      buf += chunk.toString();
      if (buf.includes("\r\n\r\n")) {
        socket.removeListener("data", onData);
        resolve(buf.slice(0, buf.indexOf("\r\n\r\n") + 4));
      }
    };
    socket.on("data", onData);
  });

  return { socket, response };
}

/**
 * Read a complete unmasked server frame from the socket.
 * Returns { opcode, payload }.
 */
function readServerFrame(socket: net.Socket): Promise<{ opcode: number; payload: Buffer }> {
  return new Promise((resolve) => {
    let buf = Buffer.alloc(0);

    const tryParse = () => {
      if (buf.length < 2) return false;

      const opcode = buf[0] & 0x0f;
      let payloadLength = buf[1] & 0x7f;
      let offset = 2;

      if (payloadLength === 126) {
        if (buf.length < 4) return false;
        payloadLength = buf.readUInt16BE(2);
        offset = 4;
      } else if (payloadLength === 127) {
        if (buf.length < 10) return false;
        payloadLength = buf.readUInt32BE(6);
        offset = 10;
      }

      if (buf.length < offset + payloadLength) return false;

      const payload = buf.subarray(offset, offset + payloadLength);
      resolve({ opcode, payload: Buffer.from(payload) });
      return true;
    };

    const onData = (chunk: Buffer) => {
      buf = Buffer.concat([buf, chunk]);
      if (tryParse()) {
        socket.removeListener("data", onData);
      }
    };
    socket.on("data", onData);

    // In case data is already buffered
    tryParse();
  });
}

// ---------------------------------------------------------------------------
// Cleanup
// ---------------------------------------------------------------------------

const cleanupFns: (() => void)[] = [];

function trackCleanup(server: http.Server, ...sockets: net.Socket[]) {
  cleanupFns.push(() => {
    for (const s of sockets) {
      if (!s.destroyed) s.destroy();
    }
    server.closeAllConnections();
    server.close();
  });
}

afterEach(() => {
  for (const fn of cleanupFns) fn();
  cleanupFns.length = 0;
});

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("computeAcceptKey", () => {
  it("produces the RFC 6455 test vector", () => {
    expect(computeAcceptKey(WS_KEY)).toBe(EXPECTED_ACCEPT);
  });
});

describe("WebSocket handshake", () => {
  it("responds with HTTP 101 Switching Protocols", async () => {
    const { server, port, wsPromise } = createTestServer();
    const { socket, response } = rawConnect(port());
    trackCleanup(server, socket);

    const resp = await response;
    await wsPromise;

    expect(resp).toContain("HTTP/1.1 101 Switching Protocols");
  });

  it("includes correct Sec-WebSocket-Accept header", async () => {
    const { server, port, wsPromise } = createTestServer();
    const { socket, response } = rawConnect(port());
    trackCleanup(server, socket);

    const resp = await response;
    await wsPromise;

    expect(resp).toContain(`Sec-WebSocket-Accept: ${EXPECTED_ACCEPT}`);
  });

  it("echoes back Sec-WebSocket-Protocol when offered", async () => {
    const { server, port, wsPromise } = createTestServer();
    const { socket, response } = rawConnect(port(), {
      "Sec-WebSocket-Protocol": "graphql-ws, graphql-transport-ws",
    });
    trackCleanup(server, socket);

    const resp = await response;
    await wsPromise;

    expect(resp).toContain("Sec-WebSocket-Protocol: graphql-ws");
  });

  it("does not include Sec-WebSocket-Protocol when not offered", async () => {
    const { server, port, wsPromise } = createTestServer();
    const { socket, response } = rawConnect(port());
    trackCleanup(server, socket);

    const resp = await response;
    await wsPromise;

    expect(resp).not.toContain("Sec-WebSocket-Protocol:");
  });
});

describe("frame parsing", () => {
  it("parses a small text frame (<126 bytes)", async () => {
    const { server, port, wsPromise } = createTestServer();
    const { socket, response } = rawConnect(port());
    trackCleanup(server, socket);

    await response;
    const ws = await wsPromise;

    const received = new Promise<string>((resolve) => {
      ws.on("message", resolve);
    });

    const payload = Buffer.from("hello");
    socket.write(createMaskedFrame(OP_TEXT, payload));

    const msg = await received;
    expect(msg).toBe("hello");
  });

  it("handles fragmented messages (continuation frames)", async () => {
    const { server, port, wsPromise } = createTestServer();
    const { socket, response } = rawConnect(port());
    trackCleanup(server, socket);

    await response;
    const ws = await wsPromise;

    const received = new Promise<string>((resolve) => {
      ws.on("message", resolve);
    });

    // Split "hello world" across 3 frames:
    //   Frame 1: opcode=0x1 (text), FIN=0, payload="hello"
    //   Frame 2: opcode=0x0 (continuation), FIN=0, payload=" wor"
    //   Frame 3: opcode=0x0 (continuation), FIN=1, payload="ld"

    function createMaskedFragmentFrame(opcode: number, fin: boolean, payload: Buffer): Buffer {
      const maskKey = randomBytes(4);
      const masked = Buffer.from(payload);
      for (let i = 0; i < masked.length; i++) {
        masked[i] ^= maskKey[i % 4];
      }
      const header = Buffer.alloc(2);
      header[0] = (fin ? 0x80 : 0x00) | opcode;
      header[1] = 0x80 | payload.length;
      return Buffer.concat([header, maskKey, masked]);
    }

    // First frame: text opcode, FIN=0
    socket.write(createMaskedFragmentFrame(0x1, false, Buffer.from("hello")));
    // Continuation frame: opcode=0, FIN=0
    socket.write(createMaskedFragmentFrame(0x0, false, Buffer.from(" wor")));
    // Final continuation frame: opcode=0, FIN=1
    socket.write(createMaskedFragmentFrame(0x0, true, Buffer.from("ld")));

    const msg = await received;
    expect(msg).toBe("hello world");
  });

  it("parses a medium text frame (126-65535 bytes, extended 16-bit length)", async () => {
    const { server, port, wsPromise } = createTestServer();
    const { socket, response } = rawConnect(port());
    trackCleanup(server, socket);

    await response;
    const ws = await wsPromise;

    const received = new Promise<string>((resolve) => {
      ws.on("message", resolve);
    });

    // Create a payload of exactly 300 bytes
    const text = "A".repeat(300);
    const payload = Buffer.from(text);
    socket.write(createMaskedFrame(OP_TEXT, payload));

    const msg = await received;
    expect(msg).toBe(text);
    expect(msg.length).toBe(300);
  });

  it("responds to ping with pong", async () => {
    const { server, port, wsPromise } = createTestServer();
    const { socket, response } = rawConnect(port());
    trackCleanup(server, socket);

    await response;
    await wsPromise;

    const frameProm = readServerFrame(socket);

    const pingPayload = Buffer.from("ping-data");
    socket.write(createMaskedFrame(OP_PING, pingPayload));

    const frame = await frameProm;
    expect(frame.opcode).toBe(OP_PONG);
    expect(frame.payload.toString()).toBe("ping-data");
  });

  it("echoes close frame back to client", async () => {
    const { server, port, wsPromise } = createTestServer();
    const { socket, response } = rawConnect(port());
    trackCleanup(server, socket);

    await response;
    const ws = await wsPromise;
    ws.on("error", () => {});

    const frameProm = readServerFrame(socket);

    // Build a close frame with code 1000 and reason "bye"
    const reason = Buffer.from("bye");
    const closePayload = Buffer.alloc(2 + reason.length);
    closePayload.writeUInt16BE(1000, 0);
    reason.copy(closePayload, 2);

    socket.write(createMaskedFrame(OP_CLOSE, closePayload));

    const frame = await frameProm;
    expect(frame.opcode).toBe(OP_CLOSE);
    // Close frame should contain code 1000
    expect(frame.payload.readUInt16BE(0)).toBe(1000);
    expect(frame.payload.subarray(2).toString()).toBe("bye");
  });
});

describe("server-side frame sending", () => {
  it("sends an unmasked text frame that the client can read", async () => {
    const { server, port, wsPromise } = createTestServer();
    const { socket, response } = rawConnect(port());
    trackCleanup(server, socket);

    await response;
    const ws = await wsPromise;

    const frameProm = readServerFrame(socket);

    ws.send("hello from server");

    const frame = await frameProm;
    expect(frame.opcode).toBe(OP_TEXT);
    expect(frame.payload.toString()).toBe("hello from server");
  });

  it("sends frames with extended 16-bit length for payloads >= 126 bytes", async () => {
    const { server, port, wsPromise } = createTestServer();
    const { socket, response } = rawConnect(port());
    trackCleanup(server, socket);

    await response;
    const ws = await wsPromise;

    const frameProm = readServerFrame(socket);

    const text = "B".repeat(200);
    ws.send(text);

    const frame = await frameProm;
    expect(frame.opcode).toBe(OP_TEXT);
    expect(frame.payload.toString()).toBe(text);
  });
});

describe("connection lifecycle", () => {
  it("emits close event when client sends close frame", async () => {
    const { server, port, wsPromise } = createTestServer();
    const { socket, response } = rawConnect(port());
    trackCleanup(server, socket);

    await response;
    const ws = await wsPromise;
    ws.on("error", () => {});

    const closeEvent = new Promise<{ code: number; reason: string }>((resolve) => {
      ws.on("close", (code: number, reason: string) => {
        resolve({ code, reason });
      });
    });

    const closePayload = Buffer.alloc(2);
    closePayload.writeUInt16BE(1000, 0);
    socket.write(createMaskedFrame(OP_CLOSE, closePayload));

    const { code, reason } = await closeEvent;
    expect(code).toBe(1000);
    expect(reason).toBe("");
    expect(ws.isClosed).toBe(true);
  });

  it("server close sends close frame and marks connection closed", async () => {
    const { server, port, wsPromise } = createTestServer();
    const { socket, response } = rawConnect(port());
    trackCleanup(server, socket);

    await response;
    const ws = await wsPromise;
    // Suppress errors from the WS connection during socket teardown
    ws.on("error", () => {});

    const frameProm = readServerFrame(socket);

    ws.close(1001, "going away");

    const frame = await frameProm;
    expect(frame.opcode).toBe(OP_CLOSE);
    expect(frame.payload.readUInt16BE(0)).toBe(1001);
    expect(frame.payload.subarray(2).toString()).toBe("going away");
    expect(ws.isClosed).toBe(true);

    // Destroy the client socket before the server's 100ms destroy timeout
    // fires, avoiding ECONNRESET on the server side.
    socket.destroy();
    await new Promise((r) => setTimeout(r, 150));
  });

  it("send() is a no-op after close", async () => {
    const { server, port, wsPromise } = createTestServer();
    const { socket, response } = rawConnect(port());
    trackCleanup(server, socket);

    await response;
    const ws = await wsPromise;
    ws.on("error", () => {});

    ws.close();
    // Should not throw
    ws.send("this should be ignored");
    expect(ws.isClosed).toBe(true);

    socket.destroy();
    await new Promise((r) => setTimeout(r, 150));
  });

  it("close() is a no-op when already closed", async () => {
    const { server, port, wsPromise } = createTestServer();
    const { socket, response } = rawConnect(port());
    trackCleanup(server, socket);

    await response;
    const ws = await wsPromise;
    ws.on("error", () => {});

    ws.close(1000, "first close");
    expect(ws.isClosed).toBe(true);

    // Second close should be a no-op (branch: close when already closed)
    ws.close(1001, "second close");
    expect(ws.isClosed).toBe(true);

    socket.destroy();
    await new Promise((r) => setTimeout(r, 150));
  });

  it("destroy() is a no-op when already closed", async () => {
    const { server, port, wsPromise } = createTestServer();
    const { socket, response } = rawConnect(port());
    trackCleanup(server, socket);

    await response;
    const ws = await wsPromise;
    ws.on("error", () => {});

    ws.close(1000, "closed");
    expect(ws.isClosed).toBe(true);

    // destroy should be a no-op (branch: destroy when already closed)
    ws.destroy();
    expect(ws.isClosed).toBe(true);

    socket.destroy();
    await new Promise((r) => setTimeout(r, 150));
  });

  it("destroy() destroys the socket and emits close 1006", async () => {
    const { server, port, wsPromise } = createTestServer();
    const { socket, response } = rawConnect(port());
    trackCleanup(server, socket);

    await response;
    const ws = await wsPromise;
    ws.on("error", () => {});

    const closeEvent = new Promise<{ code: number; reason: string }>((resolve) => {
      ws.on("close", (code: number, reason: string) => resolve({ code, reason }));
    });

    ws.destroy();

    const { code, reason } = await closeEvent;
    expect(code).toBe(1006);
    expect(reason).toBe("Connection destroyed");
    expect(ws.isClosed).toBe(true);
  });

  it("emits close 1006 when TCP socket closes unexpectedly", async () => {
    // Use a raw socket pair to directly control the server-side socket
    const [clientSide, serverSide] = await new Promise<[net.Socket, net.Socket]>((resolve) => {
      const srv = net.createServer((conn) => {
        resolve([client, conn]);
      });
      srv.listen(0);
      const port = (srv.address() as net.AddressInfo).port;
      const client = net.connect({ port, host: "127.0.0.1" });
      cleanupFns.push(() => {
        if (!client.destroyed) client.destroy();
        srv.close();
      });
    });

    serverSide.on("error", () => {});
    clientSide.on("error", () => {});

    const ws = new WebSocketConnection(serverSide);
    ws.on("error", () => {});

    const closeEvent = new Promise<{ code: number; reason: string }>((resolve) => {
      ws.on("close", (code: number, reason: string) => resolve({ code, reason }));
    });

    // Destroy the server-side socket to simulate unexpected connection loss
    serverSide.destroy();

    const { code, reason } = await closeEvent;
    expect(code).toBe(1006);
    expect(reason).toBe("Connection lost");
    expect(ws.isClosed).toBe(true);
  });

  it("handles close frame with empty payload (no code)", async () => {
    const { server, port, wsPromise } = createTestServer();
    const { socket, response } = rawConnect(port());
    trackCleanup(server, socket);

    await response;
    const ws = await wsPromise;
    ws.on("error", () => {});

    const closeEvent = new Promise<{ code: number; reason: string }>((resolve) => {
      ws.on("close", (code: number, reason: string) => resolve({ code, reason }));
    });

    // Send a close frame with empty payload (no status code)
    socket.write(createMaskedFrame(OP_CLOSE, Buffer.alloc(0)));

    const { code, reason } = await closeEvent;
    expect(code).toBe(1005);
    expect(reason).toBe("");
  });

  it("ignores unsolicited pong frames", async () => {
    const { server, port, wsPromise } = createTestServer();
    const { socket, response } = rawConnect(port());
    trackCleanup(server, socket);

    await response;
    const ws = await wsPromise;

    // Send unsolicited pong — should be silently ignored
    socket.write(createMaskedFrame(OP_PONG, Buffer.from("pong-data")));

    // Then send a text message to confirm parsing continues
    const received = new Promise<string>((resolve) => {
      ws.on("message", resolve);
    });
    socket.write(createMaskedFrame(OP_TEXT, Buffer.from("after-pong")));

    const msg = await received;
    expect(msg).toBe("after-pong");
  });

  it("writeFrame is a no-op when socket is already destroyed", async () => {
    const { server, port, wsPromise } = createTestServer();
    const { socket, response } = rawConnect(port());
    trackCleanup(server, socket);

    await response;
    const ws = await wsPromise;
    ws.on("error", () => {});

    // Destroy the underlying socket
    socket.destroy();
    // Wait for the destroy to propagate
    await new Promise((r) => setTimeout(r, 50));

    // send() calls writeFrame internally — should not throw
    // The ws is not closed yet (closed flag is separate from socket.destroyed)
    // We need to access a fresh connection and destroy its socket
    // Actually, socket.destroy fires the "close" event which sets closed=true.
    // So let's test this differently: use a connection where socket.destroyed
    // is true but closed might not be set yet.
    // The writeFrame guard is tested implicitly by other tests, but let's
    // verify send on a destroyed socket doesn't throw.
    expect(() => ws.send("test")).not.toThrow();
  });

  it("handles binary/unknown opcode frames by ignoring them", async () => {
    const { server, port, wsPromise } = createTestServer();
    const { socket, response } = rawConnect(port());
    trackCleanup(server, socket);

    await response;
    const ws = await wsPromise;

    const OP_BINARY = 0x2;
    // Send a binary frame — should be silently ignored
    socket.write(createMaskedFrame(OP_BINARY, Buffer.from("binary-data")));

    // Then send a text message to confirm parsing continues
    const received = new Promise<string>((resolve) => {
      ws.on("message", resolve);
    });
    socket.write(createMaskedFrame(OP_TEXT, Buffer.from("after-binary")));

    const msg = await received;
    expect(msg).toBe("after-binary");
  });
});

describe("upgradeToWebSocket", () => {
  it("rejects upgrade when Sec-WebSocket-Key header is missing", async () => {
    // Create a separate server that catches the throw from upgradeToWebSocket
    let caughtError: Error | null = null;
    const server = http.createServer();
    server.on("connection", (socket) => {
      socket.on("error", () => {});
    });
    server.on("upgrade", (req, socket) => {
      socket.on("error", () => {});
      try {
        upgradeToWebSocket(req, socket as net.Socket);
      } catch (err) {
        caughtError = err as Error;
      }
    });
    server.listen(0);
    const port = (server.address() as net.AddressInfo).port;

    const socket = net.connect({ port, host: "127.0.0.1" });
    socket.on("error", () => {});
    trackCleanup(server, socket);

    const response = new Promise<string>((resolve) => {
      let buf = "";
      socket.on("data", (chunk: Buffer) => {
        buf += chunk.toString();
        if (buf.includes("\r\n\r\n")) {
          resolve(buf);
        }
      });
    });

    socket.write(
      "GET / HTTP/1.1\r\n" +
        "Host: localhost\r\n" +
        "Upgrade: websocket\r\n" +
        "Connection: Upgrade\r\n" +
        "Sec-WebSocket-Version: 13\r\n" +
        "\r\n",
    );

    const resp = await response;
    expect(resp).toContain("400 Bad Request");
    // Wait for server to process
    await new Promise((r) => setTimeout(r, 50));
    expect(caughtError).not.toBeNull();
    expect(caughtError!.message).toBe("Missing Sec-WebSocket-Key header");
  });
});

async function boundedPeer(
  limits = {
    maxMessageBytes: 1024 * 1024,
    maxBufferedBytes: 2 * 1024 * 1024,
    maxWriteBytes: 1024 * 1024,
  },
) {
  const { server, port, wsPromise } = createTestServer(limits);
  const client = await connectWebSocket(`http://127.0.0.1:${port()}`, "/");
  const ws = await wsPromise;
  ws.on("error", () => {});
  cleanupFns.push(() => {
    client.destroy();
    ws.destroy();
    server.close();
  });
  return { client, ws };
}

describe("bounded real socket transport", () => {
  it("rejects unsafe 64-bit advertised length before waiting for its body", async () => {
    const { client } = await boundedPeer();
    const header = Buffer.alloc(10);
    header[0] = 0x81;
    header[1] = 0xff;
    header.writeBigUInt64BE(2n ** 53n, 2);
    client.sendRawFrame(header);
    expect((await client.waitForCloseFrame(1000)).code).toBe(1009);
  });
  it("rejects cumulative fragments exceeding the message cap", async () => {
    const { client } = await boundedPeer();
    const first = createMaskedFrame(OP_TEXT, Buffer.alloc(60000, 65));
    first[0] &= 0x7f;
    const next = createMaskedFrame(0, Buffer.alloc(60000, 65));
    next[0] &= 0x7f;
    client.sendRawFrame(first);
    for (let i = 0; i < 18; i++) client.sendRawFrame(next);
    expect((await client.waitForCloseFrame(1000)).code).toBe(1009);
  });
  it("bounds writes to a paused real peer", async () => {
    const { client, ws } = await boundedPeer({
      maxMessageBytes: 1024,
      maxBufferedBytes: 2048,
      maxWriteBytes: 16,
    });
    client.pauseReads();
    ws.send("x".repeat(17));
    expect(ws.isClosed).toBe(true);
    client.resumeReads();
    expect((await client.waitForCloseFrame(1000)).code).toBe(1009);
  });
  it.each([127, 70000])("roundtrips %i-byte text using the shared client", async (length) => {
    const { client, ws } = await boundedPeer();
    ws.on("message", (message: string) => ws.send(message));
    client.send("a".repeat(length));
    expect((await client.waitForMessages(1))[0]).toHaveLength(length);
  });
});

describe("async sends and framing control", () => {
  it("settles sends after writing and rejects after close", async () => {
    const { client, ws } = await boundedPeer();
    await ws.sendAsync("hello");
    expect(await client.waitForMessages(1)).toEqual(["hello"]);
    ws.close();
    await expect(ws.sendAsync("later")).rejects.toThrow("closed");
  });

  it.each(["abort", "destroy"] as const)("rejects an outstanding write on %s", async (action) => {
    const { client, ws } = await boundedPeer();
    client.pauseReads();
    const controller = new AbortController();
    const result = expect(ws.sendAsync("x".repeat(500000), controller.signal)).rejects.toThrow();
    if (action === "abort") controller.abort();
    else ws.destroy();
    await result;
  });

  it("rejects already aborted writes without delivering them", async () => {
    const { client, ws } = await boundedPeer();
    await expect(ws.sendAsync("no", AbortSignal.abort())).rejects.toThrow("aborted");
    await ws.sendAsync("yes");
    expect(await client.waitForMessages(1)).toEqual(["yes"]);
  });

  it("counts outstanding writes before their callbacks", async () => {
    const { client, ws } = await boundedPeer({
      maxMessageBytes: 1024,
      maxBufferedBytes: 2048,
      maxWriteBytes: 16,
    });
    client.pauseReads();
    const first = expect(ws.sendAsync("12345678")).rejects.toThrow();
    const second = expect(ws.sendAsync("12345678")).rejects.toThrow("limit");
    await Promise.all([first, second]);
    client.resumeReads();
    expect((await client.waitForCloseFrame()).code).toBe(1009);
  });

  it("answers ping between fragments and emits one close", async () => {
    const { server, port, wsPromise } = createTestServer();
    const { socket, response } = rawConnect(port());
    trackCleanup(server, socket);
    await response;
    const ws = await wsPromise;
    const first = createMaskedFrame(OP_TEXT, Buffer.from("hel"));
    first[0] &= 0x7f;
    socket.write(first);
    const pong = readServerFrame(socket);
    socket.write(createMaskedFrame(OP_PING, Buffer.from("ping")));
    expect((await pong).opcode).toBe(OP_PONG);
    const message = new Promise<string>((resolve) => ws.once("message", resolve));
    socket.write(createMaskedFrame(0, Buffer.from("lo")));
    expect(await message).toBe("hello");
    let closes = 0;
    ws.on("close", () => {
      closes++;
    });
    const closed = new Promise<void>((resolve) => ws.once("close", resolve));
    ws.close();
    ws.close();
    ws.destroy();
    await closed;
    expect(closes).toBe(1);
  });

  it.each([
    Buffer.from([0x81, 0]), // missing client mask
    Buffer.from([0x09, 0x80]), // fragmented ping
    Buffer.from([0x80, 0x80]), // unexpected continuation
    Buffer.from([0x89, 0xfe]), // oversized control
    Buffer.from([0xc1, 0x80]), // reserved bit
    Buffer.from([0x81, 0xfe, 0, 1]), // noncanonical length
  ])("closes protocol violations before their body arrives (%j)", async (frame) => {
    const { client } = await boundedPeer();
    client.sendRawFrame(frame);
    expect((await client.waitForCloseFrame()).code).toBe(1002);
  });

  it("enforces parser bytes independently of message bytes", async () => {
    const { client } = await boundedPeer({
      maxMessageBytes: 1024,
      maxBufferedBytes: 32,
      maxWriteBytes: 1024,
    });
    client.sendRawFrame(Buffer.from([0x81, 0xfe, 0, 128]));
    expect((await client.waitForCloseFrame()).code).toBe(1009);
  });

  it("masks client-role output and accepts server-role input", async () => {
    const { server, port, wsPromise } = createTestServer();
    const { socket, response } = rawConnect(port());
    trackCleanup(server, socket);
    await response;
    const serverWs = await wsPromise;
    const clientWs = new WebSocketConnection(socket, { maskOutgoing: true });
    clientWs.on("error", () => {});
    serverWs.on("error", () => {});
    const received = new Promise<string>((resolve) => serverWs.once("message", resolve));
    await clientWs.sendAsync("client");
    expect(await received).toBe("client");
    const reply = new Promise<string>((resolve) => clientWs.once("message", resolve));
    await serverWs.sendAsync("server");
    expect(await reply).toBe("server");
  });
});

describe("close reason UTF-8 boundary", () => {
  it("truncates a multibyte reason at a complete code point", async () => {
    const { server, port, wsPromise } = createTestServer();
    const { socket, response } = rawConnect(port());
    trackCleanup(server, socket);
    await response;
    const ws = await wsPromise;
    ws.on("error", () => {});
    const received = readServerFrame(socket);
    ws.close(1000, "😀".repeat(40));
    const frame = await received;
    expect(frame.opcode).toBe(OP_CLOSE);
    expect(frame.payload.length).toBeLessThanOrEqual(125);
    expect(frame.payload.readUInt16BE(0)).toBe(1000);
    expect(new TextDecoder("utf-8", { fatal: true }).decode(frame.payload.subarray(2))).toBe(
      "😀".repeat(30),
    );
  });
});

describe("received transport activity", () => {
  it("reports partial frame bytes and ping synchronously before message parsing", async () => {
    const { server, port, wsPromise } = createTestServer();
    const accepted = new Promise<net.Socket>((resolve) => server.once("connection", resolve));
    const { socket, response } = rawConnect(port());
    trackCleanup(server, socket);
    await response;
    const peer = await accepted;
    const ws = await wsPromise;
    ws.on("error", () => {});
    const activities: unknown[][] = [];
    const messages: string[] = [];
    const activityCounts: number[] = [];
    let activitiesAtMessage = 0;
    ws.on("activity", (...args: unknown[]) => activities.push(args));
    ws.on("message", (message: string) => {
      activitiesAtMessage = activities.length;
      messages.push(message);
    });
    async function sendChunk(bytes: Buffer) {
      const received = new Promise<void>((resolve) => peer.once("data", () => resolve()));
      socket.write(bytes);
      await received;
      activityCounts.push(activities.length);
    }
    const fragment = createMaskedFrame(OP_TEXT, Buffer.from("hel"));
    fragment[0] &= 0x7f;
    await sendChunk(fragment.subarray(0, 1));
    expect(messages).toEqual([]);
    await sendChunk(fragment.subarray(1));
    expect(messages).toEqual([]);
    const pong = readServerFrame(socket);
    await sendChunk(createMaskedFrame(OP_PING, Buffer.from("ping")));
    expect((await pong).opcode).toBe(OP_PONG);
    expect(messages).toEqual([]);
    await sendChunk(createMaskedFrame(0, Buffer.from("lo")));
    expect(messages).toEqual(["hello"]);
    expect(activityCounts).toEqual([1, 2, 3, 4]);
    expect(activitiesAtMessage).toBe(4);
    expect(activities.every((args) => args.length === 0)).toBe(true);
  });

  it("reports upstream upgrade-head bytes after the caller can subscribe", async () => {
    const server = http.createServer();
    const peers: net.Socket[] = [];
    server.on("connection", (socket) => {
      peers.push(socket);
      socket.on("error", () => {});
    });
    server.on("upgrade", (req, socket) => {
      const key = req.headers["sec-websocket-key"];
      if (!key) throw new Error("Missing key");
      // One write ensures text bytes accompany the HTTP upgrade response.
      socket.write(
        Buffer.concat([
          Buffer.from(
            `HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: ${computeAcceptKey(key)}\r\n\r\n`,
          ),
          Buffer.from([0x81, 2, 104, 105]),
        ]),
      );
    });
    await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
    const address = server.address();
    if (!address || typeof address === "string") throw new Error("No server address");
    cleanupFns.push(() => {
      for (const peer of peers) peer.destroy();
      server.close();
    });
    const controller = new AbortController();
    cleanupFns.push(() => controller.abort());
    const ws = await connectUpstreamWebSocket(
      new URL(`http://127.0.0.1:${address.port}/`),
      {},
      {},
      controller.signal,
    );
    let activities = 0;
    ws.on("activity", () => {
      activities++;
    });
    const message = await new Promise<string>((resolve) => ws.once("message", resolve));
    expect(message).toBe("hi");
    expect(activities).toBe(1);
  });
});
